version: "3"
services:
  nowlog-backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
